# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbf887c2a658284ac8bfe814100fcd6fb4d31a601406948a64f9878e259d174490f0cb7d3f7fb15030f0cfaf2a276b87ff95df6c73b302094828d263dd80f419

test:
  secret_key_base: 1e022ecb21b7c06785e1fc16c43de891e397e0bf84df35b4f8e168a1d797e48db41cc8bb807fc9948aac3c4c83fdb3ceae077f33fffc5c562422aa846629226d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
